=== dlozanonav/RepasoXSD/XSD/lastTwenty-20250605/lastTwenty.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="NameType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="lang" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:element name="CrossSectionalData">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Header">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="tipo-id" name="ID"/>
              <xs:element type="xs:boolean" name="Test"/>

              <xs:element name="Name" type="NameType" maxOccurs="unbounded"/>
              <xs:element type="xs:dateTime" name="Prepared"/>
              <xs:element name="Sender">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Name" type="NameType"/>
                    <xs:element name="Contact">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Name" type="NameType"/>
                          <xs:element type="tipo-email" name="Email"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="id"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="DataSet">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Group">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Section" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="TBA_DETAIL" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="tipo-mayus" name="INCLUSION_EXCLUSION_FLAG" use="optional"/>
                                  <xs:attribute type="tipo-valM" name="AMT_ACCEPTED_PAR" use="optional"/>
                                  <xs:attribute type="xs:string" name="SECURITY_DESCRIPTION" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="DR_DETAIL" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:string" name="INCLUSION_EXCLUSION_FLAG" use="optional"/>
                                  <xs:attribute type="xs:string" name="AMT_ACCEPTED_PAR" use="optional"/>
                                  <xs:attribute type="tipo-security" name="SECURITY_DESCRIPTION" use="optional"/>
                                  <xs:attribute type="tipo-mayus" name="OPERATION_DIRECTION" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="AUCTION_STATUS" use="optional"/>
                        <xs:attribute type="xs:string" name="OPERATION_ID" use="optional"/>
                        <xs:attribute type="xs:date" name="OPERATION_DATE" use="optional"/>
                        <xs:attribute type="xs:string" name="OPERATION_DIRECTION" use="optional"/>
                        <xs:attribute type="xs:string" name="OPERATION_TYPE" use="optional"/>
                        <xs:attribute type="tipo-mayus" name="AUCTION_METHOD" use="optional"/>
                        <xs:attribute type="xs:string" name="OPERATION_RELEASE_TIME" use="optional"/>
                        <xs:attribute type="xs:time" name="OPERATION_CLOSE_TIME" use="optional"/>
                        <xs:attribute type="xs:date" name="OPERATION_SETTLEMENT_DATE" use="optional"/>
                        <xs:attribute type="tipo-mayus" name="CLASS_TYPE" use="optional"/>
                        <xs:attribute type="xs:string" name="NOTE" use="optional"/>
                        <xs:attribute type="xs:string" name="TOTAL_AMT_SUBMITTED_ORIGINAL_FACE" use="optional"/>
                        <xs:attribute type="xs:string" name="TOTAL_AMT_ACCEPTED_ORIGINAL_FACE" use="optional"/>
                        <xs:attribute type="xs:string" name="TOTAL_AMT_SUBMITTED_CURRENT_FACE" use="optional"/>
                        <xs:attribute type="xs:string" name="TOTAL_AMT_ACCEPTED_CURRENT_FACE" use="optional"/>
                        <xs:attribute type="tipo-valM" name="TOTAL_AMT_SUBMITTED_PAR" use="optional"/>
                        <xs:attribute type="tipo-valM" name="TOTAL_AMT_ACCEPTED_PAR" use="optional"/>
                        <xs:attribute type="tipo-mayus" name="OBS_CONF" use="optional"/>
                        <xs:attribute type="xs:dateTime" name="LAST_UPDATED" use="optional"/>
                        <xs:attribute type="xs:time" name="START_TIME" use="optional"/>
                        <xs:attribute type="xs:time" name="END_TIME" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="tipo-mayus" name="AVAILABILITY"/>
                  <xs:attribute type="tipo-mayus" name="DISCLAIMER"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="type"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Restricciones -->
  <xs:simpleType name="tipo-id">
    <xs:restriction base="xs:string">
      <xs:pattern value="AMBS\d{14}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipo-email">
    <xs:restriction base="xs:string">
      <xs:pattern value=".{1,64}@.{1,59}\.[a-z]{2,3}"/> <!-- Cuando pones el . y la cantidad quiere decir que puedes meter cualquier caracter antes del arroba incluido el punto, para obligar a poner un punto es con \. si no lo pones el punto lo pilla como si indicaras que puedes poner cualquier caracter -->
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipo-mayus">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{1}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="tipo-valM">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1000000"/>
      <xs:maxInclusive value="20000000000"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipo-security">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z0-9]{4} [0-9](\.[0-9])? \d{2}/\d{2}"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== dlozanonav/RepasoXSD/XSD/lastTwenty-20250605/lastTwenty.xml
<?xml version="1.0" encoding="UTF-8"?>
<CrossSectionalData  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="lastTwenty.xsd">
    <Header>
        <ID>AMBS20211028155737</ID>
        <Test>false</Test>
        <Name lang="en">
            Federal Reserve Bank of New York - AMBS Results
        </Name>
        <Prepared>2021-10-28T11:57:37-04:00</Prepared>
        <Sender id="FRBNY">
            <Name lang="en">Federal Reserve Bank of New York</Name>
            <Contact>
                <Name lang="en">Digital Strategy</Name>
                <Email>ny.webcommunications@ny.frb.org</Email>
            </Contact>
        </Sender>
    </Header>
    <DataSet type="DataSetType">
        <Group AVAILABILITY="A" DISCLAIMER="G">


            <Section AUCTION_STATUS="Results" OPERATION_ID="OR 102821 1" OPERATION_DATE="2021-10-28"
                     OPERATION_DIRECTION="P" OPERATION_TYPE="Outright TBA Purchase" AUCTION_METHOD="M"
                     OPERATION_RELEASE_TIME="10:00:01Z" OPERATION_CLOSE_TIME="10:20:00Z"
                     OPERATION_SETTLEMENT_DATE="2021-11-10" CLASS_TYPE="A" NOTE="" TOTAL_AMT_SUBMITTED_ORIGINAL_FACE=""
                     TOTAL_AMT_ACCEPTED_ORIGINAL_FACE="" TOTAL_AMT_SUBMITTED_CURRENT_FACE=""
                     TOTAL_AMT_ACCEPTED_CURRENT_FACE="" TOTAL_AMT_SUBMITTED_PAR="6266000000"
                     TOTAL_AMT_ACCEPTED_PAR="3485000000" OBS_CONF="F" LAST_UPDATED="2021-10-28T10:21:17-04:00">
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="1457000000"
                            SECURITY_DESCRIPTION="FNCL 2 11/21"/>
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="2028000000"
                            SECURITY_DESCRIPTION="FNCL 2.5 11/21"/>
            </Section>


            <Section AUCTION_STATUS="Results" OPERATION_ID="OR 102821 3" OPERATION_DATE="2021-10-28"
                     OPERATION_DIRECTION="P" OPERATION_TYPE="Outright TBA Purchase" AUCTION_METHOD="M"
                     OPERATION_RELEASE_TIME="11:30:01Z" OPERATION_CLOSE_TIME="11:50:00Z"
                     OPERATION_SETTLEMENT_DATE="2021-11-18" CLASS_TYPE="C" NOTE="" TOTAL_AMT_SUBMITTED_ORIGINAL_FACE=""
                     TOTAL_AMT_ACCEPTED_ORIGINAL_FACE="" TOTAL_AMT_SUBMITTED_CURRENT_FACE=""
                     TOTAL_AMT_ACCEPTED_CURRENT_FACE="" TOTAL_AMT_SUBMITTED_PAR="4640000000"
                     TOTAL_AMT_ACCEPTED_PAR="2343000000" OBS_CONF="F" LAST_UPDATED="2021-10-28T11:50:46-04:00">
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="770000000"
                            SECURITY_DESCRIPTION="G2SF 2 11/21"/>
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="1573000000"
                            SECURITY_DESCRIPTION="G2SF 2.5 11/21"/>
            </Section>


            <Section AUCTION_STATUS="Results" OPERATION_ID="OR 102721 1" OPERATION_DATE="2021-10-27"
                     OPERATION_DIRECTION="P" OPERATION_TYPE="Outright TBA Purchase" AUCTION_METHOD="M"
                     OPERATION_RELEASE_TIME="10:00:01Z" OPERATION_CLOSE_TIME="10:20:00Z"
                     OPERATION_SETTLEMENT_DATE="2021-12-16" CLASS_TYPE="B" NOTE="" TOTAL_AMT_SUBMITTED_ORIGINAL_FACE=""
                     TOTAL_AMT_ACCEPTED_ORIGINAL_FACE="" TOTAL_AMT_SUBMITTED_CURRENT_FACE=""
                     TOTAL_AMT_ACCEPTED_CURRENT_FACE="" TOTAL_AMT_SUBMITTED_PAR="2946000000"
                     TOTAL_AMT_ACCEPTED_PAR="1371000000" OBS_CONF="F" LAST_UPDATED="2021-10-27T10:21:02-04:00">
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="1115000000"
                            SECURITY_DESCRIPTION="FNCI 1.5 12/21"/>
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="256000000"
                            SECURITY_DESCRIPTION="FNCI 2 12/21"/>
            </Section>


            <Section AUCTION_STATUS="Results" OPERATION_ID="OR 102721 3" OPERATION_DATE="2021-10-27"
                     OPERATION_DIRECTION="P" OPERATION_TYPE="Outright TBA Purchase" AUCTION_METHOD="M"
                     OPERATION_RELEASE_TIME="11:30:00Z" OPERATION_CLOSE_TIME="11:50:00Z"
                     OPERATION_SETTLEMENT_DATE="2021-11-10" CLASS_TYPE="A" NOTE="" TOTAL_AMT_SUBMITTED_ORIGINAL_FACE=""
                     TOTAL_AMT_ACCEPTED_ORIGINAL_FACE="" TOTAL_AMT_SUBMITTED_CURRENT_FACE=""
                     TOTAL_AMT_ACCEPTED_CURRENT_FACE="" TOTAL_AMT_SUBMITTED_PAR="7271000000"
                     TOTAL_AMT_ACCEPTED_PAR="3488000000" OBS_CONF="F" LAST_UPDATED="2021-10-27T11:50:53-04:00">
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="1454000000"
                            SECURITY_DESCRIPTION="FNCL 2 11/21"/>
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="2034000000"
                            SECURITY_DESCRIPTION="FNCL 2.5 11/21"/>
            </Section>


            <Section AUCTION_STATUS="Results" OPERATION_ID="OR 102621 1" OPERATION_DATE="2021-10-26"
                     OPERATION_DIRECTION="P" OPERATION_TYPE="Outright TBA Purchase" AUCTION_METHOD="M"
                     OPERATION_RELEASE_TIME="10:00:00Z" OPERATION_CLOSE_TIME="10:20:00Z"
                     OPERATION_SETTLEMENT_DATE="2021-11-10" CLASS_TYPE="A" NOTE="" TOTAL_AMT_SUBMITTED_ORIGINAL_FACE=""
                     TOTAL_AMT_ACCEPTED_ORIGINAL_FACE="" TOTAL_AMT_SUBMITTED_CURRENT_FACE=""
                     TOTAL_AMT_ACCEPTED_CURRENT_FACE="" TOTAL_AMT_SUBMITTED_PAR="8119000000"
                     TOTAL_AMT_ACCEPTED_PAR="3490000000" OBS_CONF="F" LAST_UPDATED="2021-10-26T10:20:52-04:00">
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="1828000000"
                            SECURITY_DESCRIPTION="FNCL 2 11/21"/>
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="1662000000"
                            SECURITY_DESCRIPTION="FNCL 2.5 11/21"/>
            </Section>


            <Section AUCTION_STATUS="Results" OPERATION_ID="OR 102621 3" OPERATION_DATE="2021-10-26"
                     OPERATION_DIRECTION="P" OPERATION_TYPE="Outright TBA Purchase" AUCTION_METHOD="M"
                     OPERATION_RELEASE_TIME="11:30:01Z" OPERATION_CLOSE_TIME="11:50:00Z"
                     OPERATION_SETTLEMENT_DATE="2021-11-18" CLASS_TYPE="C" NOTE="" TOTAL_AMT_SUBMITTED_ORIGINAL_FACE=""
                     TOTAL_AMT_ACCEPTED_ORIGINAL_FACE="" TOTAL_AMT_SUBMITTED_CURRENT_FACE=""
                     TOTAL_AMT_ACCEPTED_CURRENT_FACE="" TOTAL_AMT_SUBMITTED_PAR="4810000000"
                     TOTAL_AMT_ACCEPTED_PAR="2343000000" OBS_CONF="F" LAST_UPDATED="2021-10-26T11:50:43-04:00">
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="1100000000"
                            SECURITY_DESCRIPTION="G2SF 2 11/21"/>
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="1243000000"
                            SECURITY_DESCRIPTION="G2SF 2.5 11/21"/>
            </Section>


            <Section AUCTION_STATUS="Results" OPERATION_ID="OR 102521 1" OPERATION_DATE="2021-10-25"
                     OPERATION_DIRECTION="P" OPERATION_TYPE="Outright TBA Purchase" AUCTION_METHOD="M"
                     OPERATION_RELEASE_TIME="10:00:01Z" OPERATION_CLOSE_TIME="10:20:00Z"
                     OPERATION_SETTLEMENT_DATE="2021-11-10" CLASS_TYPE="A" NOTE="" TOTAL_AMT_SUBMITTED_ORIGINAL_FACE=""
                     TOTAL_AMT_ACCEPTED_ORIGINAL_FACE="" TOTAL_AMT_SUBMITTED_CURRENT_FACE=""
                     TOTAL_AMT_ACCEPTED_CURRENT_FACE="" TOTAL_AMT_SUBMITTED_PAR="5553000000"
                     TOTAL_AMT_ACCEPTED_PAR="3488000000" OBS_CONF="F" LAST_UPDATED="2021-10-25T10:20:52-04:00">
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="2020000000"
                            SECURITY_DESCRIPTION="FNCL 2 11/21"/>
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="1468000000"
                            SECURITY_DESCRIPTION="FNCL 2.5 11/21"/>
            </Section>


            <Section AUCTION_STATUS="Results" OPERATION_ID="OR 102521 3" OPERATION_DATE="2021-10-25"
                     OPERATION_DIRECTION="P" OPERATION_TYPE="Outright TBA Purchase" AUCTION_METHOD="M"
                     OPERATION_RELEASE_TIME="11:30:01Z" OPERATION_CLOSE_TIME="11:50:00Z"
                     OPERATION_SETTLEMENT_DATE="2021-12-16" CLASS_TYPE="B" NOTE="" TOTAL_AMT_SUBMITTED_ORIGINAL_FACE=""
                     TOTAL_AMT_ACCEPTED_ORIGINAL_FACE="" TOTAL_AMT_SUBMITTED_CURRENT_FACE=""
                     TOTAL_AMT_ACCEPTED_CURRENT_FACE="" TOTAL_AMT_SUBMITTED_PAR="3282000000"
                     TOTAL_AMT_ACCEPTED_PAR="1369000000" OBS_CONF="F" LAST_UPDATED="2021-10-25T11:50:42-04:00">
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="911000000"
                            SECURITY_DESCRIPTION="FNCI 1.5 12/21"/>
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="458000000"
                            SECURITY_DESCRIPTION="FNCI 2 12/21"/>
            </Section>


            <Section AUCTION_STATUS="Results" OPERATION_ID="OR 102221 1" OPERATION_DATE="2021-10-22"
                     OPERATION_DIRECTION="P" OPERATION_TYPE="Outright TBA Purchase" AUCTION_METHOD="M"
                     OPERATION_RELEASE_TIME="10:00:00Z" OPERATION_CLOSE_TIME="10:20:00Z"
                     OPERATION_SETTLEMENT_DATE="2021-11-18" CLASS_TYPE="C" NOTE="" TOTAL_AMT_SUBMITTED_ORIGINAL_FACE=""
                     TOTAL_AMT_ACCEPTED_ORIGINAL_FACE="" TOTAL_AMT_SUBMITTED_CURRENT_FACE=""
                     TOTAL_AMT_ACCEPTED_CURRENT_FACE="" TOTAL_AMT_SUBMITTED_PAR="6245000000"
                     TOTAL_AMT_ACCEPTED_PAR="2343000000" OBS_CONF="F" LAST_UPDATED="2021-10-22T10:20:52-04:00">
                <TBA_DETAIL INCLUSION_EXCLUSION_FLAG="I" AMT_ACCEPTED_PAR="1759000000"
