=== dlozanonav/RepasoXSD/XSD/mondial1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mondial" type="mondialType"/>
  <xs:complexType name="indep_dateType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="from"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="encompassedType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="continent"/>
        <xs:attribute type="tipo-percentaje" name="percentage"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ethnicgroupType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="tipo-percentaje" name="percentage" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="religionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="tipo-percentaje" name="percentage" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="borderType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="tipo-country" name="country" use="optional"/>
        <xs:attribute type="tipo-length" name="length" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="populationType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="tipo-ano" name="year" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="cityType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="tipo-longitude" name="longitude"/>
      <xs:element type="tipo-latitude" name="latitude"/>
      <xs:element type="populationType" name="population"/>
      <xs:element type="located_atType" name="located_at" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
    <xs:attribute type="xs:string" name="is_country_cap" use="optional"/>
    <xs:attribute type="xs:string" name="country" use="optional"/>
  </xs:complexType>
  <xs:complexType name="located_atType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="watertype" use="optional"/>
        <xs:attribute type="xs:string" name="lake" use="optional"/>
        <xs:attribute type="xs:string" name="sea" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="countryType">
    <xs:sequence maxOccurs="unbounded" minOccurs="0">
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:integer" name="population"/>
      <xs:element type="xs:decimal" name="population_growth"/>
      <xs:element type="xs:decimal" name="infant_mortality"/>
      <xs:element type="xs:integer" name="gdp_total"/>
      <xs:element type="xs:integer" name="gdp_agri"/>
      <xs:element type="xs:integer" name="inflation"/>
      <xs:element type="indep_dateType" name="indep_date"/>
      <xs:element type="xs:string" name="government"/>
      <xs:element type="encompassedType" name="encompassed"/>
      <xs:element type="ethnicgroupType" name="ethnicgroup" maxOccurs="unbounded" />
      <xs:element type="religionType" name="religion" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="borderType" name="border" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="cityType" name="city" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="tipo-car_code" name="car_code"/>
    <xs:attribute type="tipo-area" name="area"/>
    <xs:attribute type="xs:string" name="capital" use="required"/>
    <xs:attribute type="xs:string" name="memberships"/>
  </xs:complexType>

  <xs:complexType name="mondialType">
    <xs:sequence>
      <xs:element type="countryType" name="country" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Restricciones -->

  <xs:simpleType name="tipo-longitude">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="1"/>
      <xs:maxInclusive value="180"/>
      <xs:minExclusive value="-180"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipo-percentaje">
    <xs:restriction base="xs:integer">
      <xs:minExclusive value="0"/>
      <xs:maxInclusive value="100"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipo-country">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipo-length">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipo-ano">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{2}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="tipo-latitude">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="1"/>
      <xs:minInclusive value="-90"/>
      <xs:maxInclusive value="90"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="tipo-area">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipo-car_code">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{2}"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== dlozanonav/RepasoXSD/XSD/mondial1.xml
<?xml version="1.0" encoding="UTF-8"?>
<mondial xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="mondial1.xsd">
    <country car_code="AL" area="28750" capital="cty-Albania-Tirane" memberships="org-BSEC org-CE org-CCC org-ECE org-EBRD org-FAO org-IAEA org-IBRD org-ICAO org-Interpol org-IDA org-IFRCS org-IFC org-IFAD org-ILO org-IMO org-IMF org-IOC org-IOM org-ISO org-ICRM org-ITU org-Intelsat org-IDB org-ANC org-OSCE org-OIC org-PFP org-UN org-UNESCO org-UNIDO org-UNOMIG org-UPU org-WFTU org-WHO org-WIPO org-WMO org-WToO org-WTrO">
        <name>Albania</name>
        <population>3249136</population>
        <population_growth>1.34</population_growth>
        <infant_mortality>49.2</infant_mortality>
        <gdp_total>4100</gdp_total>
        <gdp_agri>55</gdp_agri>
        <inflation>16</inflation>
        <indep_date from="Ottoman Empire">1912-11-28</indep_date>
        <government>emerging democracy</government>
        <encompassed continent="europe" percentage="100"/>
        <ethnicgroup percentage="95">Albanian</ethnicgroup>
        <ethnicgroup percentage="3">Greek</ethnicgroup>
        <religion percentage="70">Muslim</religion>
        <religion percentage="10">Roman Catholic</religion>
        <religion percentage="20">Christian Orthodox</religion>
        <border country="GR" length="282"/>
        <border country="MK" length="151"/>
        <border country="MN" length="172"/>
        <border country="KO" length="112"/>

        <city id="cty-Albania-Tirane" is_country_cap="yes" country="AL">
            <name>Tirane</name>
            <longitude>19.8</longitude>
            <latitude>41.3</latitude>
            <population year="87">192000</population>
        </city>
        <city id="stadt-Shkoder-AL-AL" country="AL">
            <name>Shkoder</name>
            <longitude>19.2</longitude>
            <latitude>42.2</latitude>
            <population year="87">62000</population>
            <located_at watertype="lake" lake="lake-Skutarisee"/>
        </city>
        <city id="stadt-Durres-AL-AL" country="AL">
            <name>Durres</name>
            <longitude>19.3</longitude>
            <latitude>41.3</latitude>
            <population year="87">60000</population>
            <located_at watertype="sea" sea="sea-Mittelmeer"/>
        </city>
        <city id="stadt-Vlore-AL-AL" country="AL">
            <name>Vlore</name>
            <longitude>19.3</longitude>
            <latitude>40.3</latitude>
            <population year="87">56000</population>
            <located_at watertype="sea" sea="sea-Mittelmeer"/>
        </city>
        <city id="stadt-Elbasan-AL-AL" country="AL">
            <name>Elbasan</name>
            <longitude>20.1</longitude>
            <latitude>41.1</latitude>
            <population year="87">53000</population>
        </city>
        <city id="stadt-Korce-AL-AL" country="AL">
            <name>Korce</name>
            <longitude>20.5</longitude>
            <latitude>40.4</latitude>
            <population year="87">52000</population>
        </city>
    </country>
</mondial>
